### ISSUE TITLE
다이얼로그 텍스트 수정, ktx 날짜 조회 범위 확대, snackbar 텍스트 수정, logout 아이콘 수정

### ISSUE THREAD

**Issue by 2021jian** [I-Taxi/itaxi#297]
**Description**
- 다이얼로그 텍스트 출발지를 도착지로 수정
- ktx 날짜 조회 범위 확대
- snackbar 상단의 라는 단어 추가
- logout 아이콘 수정

**Todo**
- [x] 다이얼로그 텍스트 출발지를 도착지로 수정
- [x] ktx 날짜 조회 범위 확대
- [x]  snackbar 상단의 라는 단어 추가
- [x] logout 아이콘 수정
