### ISSUE TITLE
프로젝트 2기 기본 세팅

### ISSUE THREAD

**Issue by chanhk-im** [I-Taxi/itaxi#64]
**Description**

- 2기 front-end 프로젝트 기본 세팅

**Todo**
- [x] 작업 환경 최신화
- [x] git commit message template 생성
- [x] develop 브랜치 생성
